name: Paper Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-22.04
    env:
      PYTHONUNBUFFERED: "1"
      MPLBACKEND: Agg
      PHOSPHONETWORKS_FIGURES_DIR: ${{ github.workspace }}/figures
      # Keep dataset inside workspace so caching/restores are predictable
      PHOSPHONETWORKS_DATA_DIR: ${{ github.workspace }}/.cache/phosphonetworks_dataset

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libgraphviz-dev pkg-config

      - name: Cache manuscript dataset
        id: cache-dataset
        uses: actions/cache@v4
        with:
          path: ${{ env.PHOSPHONETWORKS_DATA_DIR }}
          key: ${{ runner.os }}-phosphonetworks-dataset-v1
          restore-keys: |
            ${{ runner.os }}-phosphonetworks-dataset-

      - name: Install package and test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install . pytest

      - name: Run paper pipeline test
        run: |
          # Your test will download/populate $PHOSPHONETWORKS_DATA_DIR if empty
          python -m pytest tests/test_paper_pipeline.py